--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: sikander
--



--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: sikander
--

INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (1, 'How to Train Your Dragon (2025)', 'How to Train Your Dragon (2025):  Hiccup, now a seasoned chief, faces a new threat to Berk and the dragons, forcing him to confront his past and unite his people and dragons against a powerful, mysterious enemy who seeks to control the dragons for their own nefarious purposes.  The film focuses on themes of leadership, responsibility, and the ever-evolving relationship between Vikings and dragons.', 'https://image.tmdb.org/t/p/w500/9gryX1HZ3C45X94BBs2FOZGasU2.jpg', '2025-08-10', 'https://katmoviehd.run/how-to-train-your-dragon-2025-hindi-imax/', NULL, 'How to Train Your Dragon (2025) BluRay IMAX 4K [Hindi Dubbed (DD 5.1) & English] Dual Audio 2160p 1080p 720p 480p HDR/DV');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (2, 'Pretty Thing (2025)', 'Pretty Thing (2025):  A seemingly perfect young woman navigates the pressures of social media fame and the cutthroat world of fashion, grappling with insecurities and uncovering hidden truths about herself and the industry that surrounds her.  Her carefully crafted image begins to crumble as she confronts the consequences of her choices.', 'https://m.media-amazon.com/images/M/MV5BOWQwZmRmMzMtYWZiNC00YTVhLWI1ZDAtZDM3MTE5ZDViYzE3XkEyXkFqcGc@._V1_SX500.jpg', '2025-08-10', 'https://katmoviehd.run/pretty-thing-2025-hindi/', NULL, 'Pretty Thing (2025) Hindi Dubbed (ORG) & English [Dual Audio] WEB-DL 1080p 720p 480p [Full Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (3, 'Freakier Friday (2025)', 'Freakier Friday (2025): A mother and daughter, constantly clashing due to generational differences, magically swap bodies. They must learn to understand each other''s perspectives and navigate the challenges of living each other''s lives, ultimately strengthening their bond.', 'https://m.media-amazon.com/images/M/MV5BY2Q0M2NmMjctODEwMi00NGIyLTk4NjUtMzBlNDAxYTZlZGJiXkEyXkFqcGc@._V1_SX300.jpg', '2025-08-10', 'https://katmoviehd.run/freakier-friday-2025-eng-1x/', NULL, 'Freakier Friday (2025) Full Movie in English [PreHD 1080p / 720p / 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (4, 'Love Hurts (2025)', 'Love Hurts (2025): Two individuals, each harboring past traumas, find themselves drawn together despite their differences and fears of vulnerability.  Their relationship unfolds amidst emotional turmoil, forcing them to confront their emotional baggage and learn to trust again.', 'https://image.tmdb.org/t/p/w500/jwp9kBtyW3kLMFIulQAihK8kGgl.jpg', '2025-08-10', 'https://katmoviehd.run/love-hurts-2025-hindi/', NULL, 'Love Hurts (2025) Hindi Dubbed (ORG) & English [Dual Audio] BluRay 1080p 720p 480p HD [Full Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (5, 'Saving Silverman (2001)', 'Saving Silverman (2001): Three friends try to sabotage their friend''s impending marriage to a woman they deem unsuitable, resulting in a series of chaotic and hilarious misadventures.', 'https://image.tmdb.org/t/p/w500/5mq8J11266ZL7HCOwDGXoaU6eIO.jpg', '2025-08-10', 'https://katmoviehd.run/saving-silverman-2001/', NULL, 'Saving Silverman (2001) Full Movie (In English 5.1 DD) + ESubs | BluRay 1080p 720p [HD x264 & 10bitHEVC]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (6, 'The Naked Gun (2025)', 'The Naked Gun (2025):  Lieutenant Frank Drebin returns to tackle a new, outlandish criminal plot that threatens global security.  His bumbling yet effective methods, coupled with his signature slapstick humor, lead him on a wild chase filled with ridiculous situations and unexpected twists.', 'https://m.media-amazon.com/images/M/MV5BNGFlNDhkNzItZjgxNC00OGYzLWFjZDAtZTJmNDY5ZmEyZDc0XkEyXkFqcGc@._V1_SX500.jpg', '2025-08-10', 'https://katmoviehd.run/the-naked-gun-2025-hin-vo/', NULL, 'The Naked Gun (2025) Full Movie in Hindi Dubbed (Unofficial) [WEBRip 1080p 720p 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (7, 'Countdown (Season 1)', 'Countdown (Season 1) Hindi Dubbed:  (Storyline unavailable without specifics of the show''s plot).', 'https://m.media-amazon.com/images/M/MV5BNTZhNmQ5MjYtZGJkYy00ZTAwLWIxYTQtNWFiZTk5ZDM4ZWZmXkEyXkFqcGc@._V1_FMjpg_UX500_.jpg', '2025-08-10', 'https://katmoviehd.run/countdown-s1/', NULL, 'Countdown (Season 1) Hindi Dubbed (ORG) [Dual Audio] All Episodes | WEB-DL 1080p 720p 480p HD [2025 Amazon Prime Series] – S1 Episode 09 Added !');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (8, 'The Pickup (2025)', 'The Pickup (2025):  A man embarks on a dangerous journey across continents, caught in a web of intrigue and deception while trying to find a missing person, only to uncover a complex conspiracy.', 'https://image.tmdb.org/t/p/w500/qhJUpgHvhtHfZGE9Thnr31q3rBY.jpg', '2025-08-10', 'https://katmoviehd.run/the-pickup-2025-hindi/', NULL, 'The Pickup (2025) Hindi Dubbed (DD 5.1) & English [Dual Audio] WEB-DL 1080p 720p 480p HD [Amazon Prime Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (9, 'The Summer I Turned Pretty (Season 3)', 'The Summer I Turned Pretty (Season 3) Hindi Dubbed: (Storyline unavailable without specifics of the show''s plot).', 'https://image.tmdb.org/t/p/w500/asFR155T7d8AZbrdKTMDPR1x1nQ.jpg', '2025-08-10', 'https://katmoviehd.run/the-summer-i-turned-pretty-s3/', NULL, 'The Summer I Turned Pretty (Season 3) Hindi Dubbed (ORG) [Dual Audio] All Episodes | WEB-DL 2160p 1080p 720p 480p HD [2025 Amazon Prime Series] – S3 Episode 05 Added');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (10, '18 Again (Season 1)', '18 Again (Season 1) Hindi Dubbed: A middle-aged man, disillusioned with his life, is magically transformed back into his 18-year-old self, giving him a second chance to rectify past mistakes and find fulfillment.', 'https://image.tmdb.org/t/p/w500/jwrumjdNdtlHRzthQEj9HmxehcR.jpg', '2025-08-10', 'https://katmoviehd.run/18-again-s01-hindi/', NULL, '18 Again (Season 1) Hindi Dubbed (ORG) WEB-DL Dual-Audio 1080p 720p 480p HD [2020 K-Drama Series] [Episode 03 Added !]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (11, 'Together (2025)', 'Together (2025): A group of diverse individuals, each facing their own personal struggles, find solace and unexpected connections in a shared community, learning about the power of friendship and resilience.', 'https://m.media-amazon.com/images/M/MV5BOWI1Mzg0OWUtNDYxYy00Mzk3LTgxMjMtYWYxZjJhMjI4NDcyXkEyXkFqcGc@._V1_SX500.jpg', '2025-08-10', 'https://katmoviehd.run/together-2025-vo-1x/', NULL, 'Together (2025) Full Movie in Hindi Dubbed (Unofficial) [CAMRip 1080p 720p 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (12, 'Materialists (2025)', 'Materialists (2025):  A satirical look at the obsession with material possessions in modern society, following individuals driven by wealth and status who eventually confront the emptiness of their pursuits.', 'https://image.tmdb.org/t/p/w500/zh4kaa2dGhVjojHulCWt3AR4b2l.jpg', '2025-08-10', 'https://katmoviehd.run/materialists-2025-hindi/', NULL, 'Materialists (2025) Hindi Dubbed (DD 5.1) & English [Dual Audio] WEB-DL 2160p 1080p 720p 480p 4K HDR SDR [Full Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (13, 'The Life of Chuck (2025', 'The Life of Chuck (2025) follows the unpredictable journey of Chuck, a seemingly ordinary man whose life takes unexpected turns, leading him on a humorous and heartwarming adventure filled with self-discovery and unlikely friendships.', 'https://image.tmdb.org/t/p/w500/zK4s2pcGiK1uZTIitEAZJBnIfN4.jpg', '2025-08-10', 'https://katmoviehd.run/the-life-of-chuck-2024/', NULL, 'The Life of Chuck (2025 Full Movie) WEB-DL 1080p 720p 480p [HD x264 & HEVC] (In English 5.1 DD) + ESubs');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (14, 'Leanne (Season 1)', 'Leanne (Season 1) follows the life of Leanne, navigating complex relationships and challenges, exploring themes of [the storyline needs more information to be accurately described].', 'https://m.media-amazon.com/images/M/MV5BNGNhNjUwMWEtNGVjNy00NmZlLWE5NjAtNWE0ZDMwMGZjODQ0XkEyXkFqcGc@._V1_FMjpg_UX400_.jpg', '2025-08-10', 'https://katmoviehd.run/leanne-s01-hindi/', NULL, 'Leanne (Season 1) Hindi Dubbed (DD 5.1) & English [Dual Audio] All Episodes | WEB-DL 1080p 720p 480p [2025 Netflix Series]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (15, 'Glass Heart (Season 1)', 'Glass Heart (Season 1) presents a multifaceted narrative likely involving a character with a "glass heart," suggesting vulnerability and perhaps a journey of emotional healing or confronting inner demons, with the multi-audio option implying an international storyline or cast.', 'https://image.tmdb.org/t/p/w500/bAyTAAtY9ccmnKgsH7xqZLyQw16.jpg', '2025-08-10', 'https://katmoviehd.run/glass-heart-s1/', NULL, 'Glass Heart (Season 1) Hindi Dubbed (DD 5.1) & English & Japanese [Multi Audio] All Episodes | WEB-DL 1080p 720p 480p [2025 Netflix Series]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (16, 'Marked (Season 1)', 'Marked (Season 1) focuses on individuals who bear a mysterious mark, leading them on a path of intrigue and possibly danger, as they uncover a larger conspiracy related to the mark''s significance.', 'https://image.tmdb.org/t/p/w500/w2C8YmxXtQ9gEYMYMQS6I1ZQRm7.jpg', '2025-08-10', 'https://katmoviehd.run/marked-s1/', NULL, 'Marked (Season 1) Hindi Dubbed (DD 5.1) & English [Dual Audio] All Episodes | WEB-DL 1080p 720p [2025 Netflix Series]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (17, 'The 47 (2024)', 'The 47 (2024) likely centers around a group of 47 individuals, possibly connected by a shared experience or facing a common threat, leading to a suspenseful or action-packed narrative.', 'https://image.tmdb.org/t/p/w500/d2bSDM4mfdQBOx7su3PhiFffnn6.jpg', '2025-08-10', 'https://katmoviehd.run/the-47-2024-hindi/', NULL, 'The 47 (2024) Hindi Dubbed (ORG) & Spanish [Dual Audio] WEB-DL 1080p 720p 480p HD [Full Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (18, 'Talchul: Project Silence (2023)', 'Talchul: Project Silence (2023) revolves around a project codenamed "Silence," hinting at a story involving secrecy, potentially espionage, technological advancement, or a mystery centered around the suppression of information or a significant event.', 'https://image.tmdb.org/t/p/w500/lZT5Cq4wkz7IeJEnz94U94xuEWD.jpg', '2025-08-10', 'https://katmoviehd.run/talchul-project-silence-2023-hindi/', NULL, 'Talchul: Project Silence (2023) Hindi Dubbed (DD 5.1) & Korean [Dual Audio] WEB-DL 1080p 720p 480p HD [Full Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (19, 'An Honest Life (2025)', 'An Honest Life (2025) depicts the life of an individual striving for honesty and integrity, exploring the challenges and conflicts that arise as they navigate moral dilemmas and complex relationships in their pursuit of an ethical life.', 'https://image.tmdb.org/t/p/w500/mvLHo4hgTpTZHwURIipEIrFrL0k.jpg', '2025-08-10', 'https://katmoviehd.run/an-honest-life-2025-hindi/', NULL, 'An Honest Life (2025) Hindi Dubbed (DD 5.1) & English [Dual Audio] WEB-DL 1080p 720p 480p HD [Full Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (20, 'The Sandman (Season 2)', 'The Sandman (Season 2) continues the adventures of Dream, the Sandman, as he navigates the realms of dreams and nightmares, facing new challenges and encountering both familiar and new characters from the mythology of the Sandman universe.', 'https://image.tmdb.org/t/p/w500/dhbqyYjLfTNAHodDDjDELzwO6F4.jpg', '2025-08-10', 'https://katmoviehd.run/the-sandman-s02/', NULL, 'The Sandman (Season 2) Hindi Dubbed (DD 5.1) [Dual Audio] | WEB-DL 2160p 1080p 720p 480p HD [2025 Netflix Series] – ( Volume 1 & 2 Episode 12 Added)');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (21, 'Elio (2025)', 'Elio (2025) likely centers around the character Elio, whose story unfolds within an unspecified genre, requiring more information for a detailed plot summary.', 'https://catimages.org/images/2025/07/31/Elio-2025-hindi-lo.jpg', '2025-08-10', 'https://katmoviehd.run/elio-2025-hindi-1x/', NULL, 'Elio (2025) Full Movie in Hindi Dubbed (Clean Audio) [WEBRip 1080p / 720p / 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (22, 'Ricki and the Flash (2015)', 'Ricki and the Flash (2015) portrays the life of a rock-and-roll singer, Ricki, who struggles to balance her musical aspirations with her personal relationships and family life, as she navigates a complex personal journey and confronts past regrets.', 'https://image.tmdb.org/t/p/w500/9hge51fXFzXP3lo83yAu3LNgUyU.jpg', '2025-08-10', 'https://katmoviehd.run/ricki-and-the-flash-2015-hindi/', NULL, 'Ricki and the Flash (2015) Hindi Dubbed (DD 5.1) & English [Dual Audio] BluRay 1080p 720p 480p HD [Full Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (23, 'Rapaces (2025)', 'Rapaces (2025) suggests a storyline involving "birds of prey" or something with a similar connotation, possibly involving a thrilling adventure or suspenseful narrative with characters who are cunning, predatory, or powerful in their own right.', 'https://m.media-amazon.com/images/M/MV5BYzcwNWRiNmEtYTAxMy00NmJjLWE5NzEtY2M3ODkyOWJhZjZhXkEyXkFqcGc@._V1_SX500.jpg', '2025-08-10', 'https://katmoviehd.run/rapaces-2025-full-movie-in-bengali-dubbed/', NULL, 'Rapaces (2025) Full Movie in Bengali Dubbed [CAMRip 1080p 720p 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (24, 'Braving Rapids (2025)', '**Braving Rapids (2025):** A group of thrill-seeking friends embarks on a white-water rafting expedition down a treacherous river, facing unexpected dangers and testing the bonds of their friendship as they fight for survival against the unforgiving power of nature.', 'https://m.media-amazon.com/images/M/MV5BNWNjYjRjZTgtYWEyZS00NTI1LWFhNDUtNmExNmQzNTQ4NzBmXkEyXkFqcGc@._V1_SX500.jpg', '2025-08-10', 'https://katmoviehd.run/braving-rapids-2025-hin-webrip-vo/', NULL, 'Braving Rapids (2025) Full Movie in Hindi Dubbed (Unofficial) [WEBRip 1080p 720p 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (25, 'Bandook (2025)', '**Bandook (2025):** In a remote village plagued by violence, a young woman armed with only her wits and a rusty rifle must protect her family and community from a ruthless gang, challenging traditional gender roles and embracing her inner strength in a desperate fight for survival.', 'https://m.media-amazon.com/images/M/MV5BMDllMTY5MmYtZDQxYS00ZTZhLTg0YjQtMjFmMjc0YTVlNmY0XkEyXkFqcGc@._V1_SX500.jpg', '2025-08-10', 'https://katmoviehd.run/bandook-2025-hin-camrip-vo/', NULL, 'Bandook (2025) Full Movie in Hindi Dubbed [CAMRIP 1080p 720p 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (26, 'No nos moverán (2024)', '**No nos moverán (2024):**  A community in a marginalized neighborhood unites to fight the imminent demolition of their homes by a powerful corporation, sparking a passionate and determined resistance that exposes corruption and challenges the forces seeking to displace them.', 'https://m.media-amazon.com/images/M/MV5BNzBkMmIyYTgtNDg3Yi00OTE4LTliZDgtYzY0NDU0MjkzYzMzXkEyXkFqcGc@._V1_FMjpg_UY400_.jpg', '2025-08-10', 'https://katmoviehd.run/no-nos-moveran-2024-hin-camrip-vo/', NULL, 'No nos moverán (2024) Full Movie in Hindi Dubbed (Unofficial) [CAMRip 1080p 720p 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (27, 'I Am Your Biggest Fan (2025)', '**I Am Your Biggest Fan (2025):** An obsessive fan''s admiration for a reclusive celebrity spirals into dangerous obsession, blurring the lines between devotion and stalking as their actions threaten the celebrity''s life and well-being.', 'https://m.media-amazon.com/images/M/MV5BMzJhODljNzktYzhiMy00ZGM2LTgxNGMtOTZjNmE0ZjM3MWI3XkEyXkFqcGc@._V1_SX500.jpg', '2025-08-10', 'https://katmoviehd.run/i-am-your-biggest-fan-2025-hin-webrip-vo/', NULL, 'I Am Your Biggest Fan (2025) Full Movie in Hindi Dubbed (Unofficial) [WEBRip 1080p 720p 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (28, 'Daisy (2024)', '**Daisy (2024):**  A young woman, haunted by a traumatic past, finds unexpected solace and connection through a stray dog she rescues, forging a powerful bond that helps her heal and confront her inner demons.', 'https://m.media-amazon.com/images/M/MV5BYTZlMTNhMGEtYzE1NS00MjViLThlZmQtMDM0Y2NmMGQ2NzQ2XkEyXkFqcGc@._V1_FMjpg_UY337_.jpg', '2025-08-10', 'https://katmoviehd.run/daisy-2024-vo/', NULL, 'Daisy (2024) Full Movie In Hindi Dubbed (Unofficial) [WEBRip 1080p 720p 480p] – 1XBET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (29, 'Houdini (2014) Extended Mini Series', '**Houdini (2014):** A biographical drama chronicling the life of the legendary escape artist Harry Houdini, exploring his daring feats, personal struggles, and the mysteries surrounding his death.', 'https://image.tmdb.org/t/p/w500/ba43f5KXfH01ipDmDR4lZSQyDkL.jpg', '2025-08-10', 'https://katmoviehd.run/houdini/', NULL, 'Houdini (2014) Extended Mini Series 720p 1080p BluRay [Hindi ORG- English ] [Dual Audio] x264 ESubs');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (30, 'My Oxford Year (2025)', '**My Oxford Year (2025):** A bright but unconventional student navigates the prestigious world of Oxford University, grappling with academic pressure, complex relationships, and the challenges of self-discovery amidst a vibrant and intellectually stimulating environment.', 'https://image.tmdb.org/t/p/w500/yUO0SIxZfmzFUEXJ3NdNIUc6a2M.jpg', '2025-08-10', 'https://katmoviehd.run/my-oxford-year-2025-hindi/', NULL, 'My Oxford Year (2025) Hindi Dubbed (DD 5.1) & English [Dual Audio] WEB-DL 1080p 720p 480p HD [Netflix Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (31, 'The Legend of Ochi (2025)', '**The Legend of Ochi (2025):**  An epic adventure unfolds as a young warrior sets out to uncover the truth behind a legendary lost city, facing mythical creatures, treacherous landscapes, and ancient prophecies in a quest to protect their people.', 'https://image.tmdb.org/t/p/w500/qYyEelO4JfOwE0Ui5KsrCE0O8UA.jpg', '2025-08-10', 'https://katmoviehd.run/the-legend-of-ochi-2025-hindi/', NULL, 'The Legend of Ochi (2025) Hindi Dubbed (DD 5.1) & English [Dual Audio] BluRay 1080p 720p 480p HD [Full Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (32, 'Star Trek: Strange New Worlds (Season 3)', '**Star Trek: Strange New Worlds (Season 3) Hindi Dubbed (ORG) | 2160p 1080p 720p 480p HD [2025] Episode 1-4 Added! ()**:  The crew of the USS Enterprise faces new and challenging missions across the galaxy, encountering strange new civilizations, formidable foes, and moral dilemmas as they explore the uncharted territories of space.  (Note: This is a description of the release, not a plot summary of a single movie.)', 'https://image.tmdb.org/t/p/w500/9tdGXi1g1e2inM19yaaiFCdYofW.jpg', '2025-08-10', 'https://katmoviehd.run/star-trek-strange-new-worlds-s03/', NULL, 'Star Trek: Strange New Worlds (Season 3) Hindi Dubbed (ORG) | 2160p 1080p 720p 480p HD [2025] Episode 1-4 Added!');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (33, 'Dracula: A Love Tale (2025)', '**Dracula: A Love Tale (2025):** A reimagining of the classic Dracula story focusing on the complex and passionate relationship between Dracula and his beloved, exploring the themes of love, sacrifice, and immortality against a backdrop of gothic romance and supernatural horror.', 'https://m.media-amazon.com/images/M/MV5BY2U5OTYxZTUtZWFjZC00NjFmLWFhYjgtYzdjNDhmZWU3OTgxXkEyXkFqcGc@._V1_SX500.jpg', '2025-08-10', 'https://katmoviehd.run/dracula-a-love-tale-2025-eng-4rb/', NULL, 'Dracula: A Love Tale (2025) Full Movie in English [CAMRip 1080p 720p 480p] – 4RABET');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (34, 'Watchmen: Chapter II (2024)', '**Watchmen: Chapter II (2024):**  A continuation of the Watchmen story, exploring new threats to society and delving deeper into the complex moral dilemmas faced by vigilantes and the corrupt systems they fight against in a world grappling with the fallout of past events.', 'https://image.tmdb.org/t/p/w500/4rBObJFpiWJOG7aIlRrOUniAkBs.jpg', '2025-08-10', 'https://katmoviehd.run/watchmen-chapter-ii-2024-hindi/', NULL, 'Watchmen: Chapter II (2024) Hindi Dubbed (DD 5.1) & English [Dual Audio] BluRay 1080p 720p 480p HD [Full Movie]');
INSERT INTO public.movies (id, title, description, poster, release_date, youtube_link, category_id, tagline) VALUES (35, '28 Years Later (2025)', '**28 Years Later (2025):**  Years after a devastating pandemic, survivors navigate a world ravaged by a relentless virus, grappling with the psychological trauma, societal collapse, and the constant threat of infection in a desperate struggle for survival.', 'https://m.media-amazon.com/images/M/MV5BNjgwYTI0YjctMWYzNS00MmI1LWI5YTctNmE1YjBkNDFlNWMxXkEyXkFqcGc@._V1_SX500.jpg', '2025-08-10', 'https://katmoviehd.run/28-years-later-2025-hin-webrip-4rb/', NULL, '28 Years Later (2025) Full Movie In Hindi Dubbed (Unofficial) [WEBRip 1080p 720p 480p] – 4RABET');


--
-- Data for Name: movies_categories; Type: TABLE DATA; Schema: public; Owner: sikander
--



--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sikander
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, false);


--
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sikander
--

SELECT pg_catalog.setval('public.movies_id_seq', 35, true);


--
-- PostgreSQL database dump complete
--

